/*
 * File: app/view/ClientDetailViewPhone.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CestaDomu.view.ClientDetailViewPhone', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.tab.Panel',
        'Ext.Menu'
    ],

    config: {
        itemId: 'clientDetailView',
        layout: {
            type: 'card',
            animation: 'fade'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 50,
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.toggleMenu('left');
                        },
                        itemId: 'hamburgerMenuButton',
                        ui: 'plain',
                        iconCls: 'list'
                    },
                    {
                        xtype: 'label',
                        itemId: 'tabName',
                        padding: '0 5 0 0'
                    },
                    {
                        xtype: 'label',
                        itemId: 'quickInfo'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Průběhy<br />péče',
                itemId: 'clientInfoContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'list',
                        flex: 50,
                        itemTpl: [
                            '{[Ext.Date.format(values.startDate, \'d. m. Y H:i\')]} {nurse}<br/>',
                            '{Name}'
                        ],
                        store: 'NurseCareStore'
                    },
                    {
                        xtype: 'container',
                        flex: 50,
                        itemId: 'nurseCareInfo',
                        margin: 5,
                        style: 'border-top: solid black 5px;',
                        layout: 'vbox',
                        scrollable: 'vertical'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Medikace',
                itemId: 'drugContainer',
                layout: 'fit',
                items: [
                    {
                        xtype: 'list',
                        itemTpl: [
                            '<span style="color: {[ values.authorizedByDoctor ? \'green\' : \'red\' ]};">{name}</span> {applicationType} {dose}<tpl if="symptom"> na {symptom}</tpl>',
                            '<tpl if="endDate">, od {[Ext.Date.format(values.startDate, \'d. m. Y\')]}</tpl><tpl if="endDate"> do {[Ext.Date.format(values.endDate, \'d. m. Y\')]}</tpl>',
                            '<tpl if="interval">, interval další aplikace: {interval}</tpl><tpl if="maxDose">, maximálně {maxDose}</tpl><tpl if="note">, {note}</tpl>'
                        ],
                        store: 'DrugStore',
                        grouped: true
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'doctorContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'list',
                        flex: 50,
                        itemTpl: [
                            '{[Ext.Date.format(values.startDate, \'d. m. Y H:i\')]} {doctor}<br/>',
                            '{medicalReporttype}'
                        ],
                        store: 'DoctorCareStore'
                    },
                    {
                        xtype: 'container',
                        flex: 50,
                        itemId: 'doctorCareInfo',
                        margin: 5,
                        style: 'border-top: solid black 5px;',
                        scrollable: 'vertical'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'consultationContainer',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'list',
                        flex: 50,
                        itemTpl: [
                            '{[Ext.Date.format(values.startDate, \'d. m. Y H:i\')]} {consultant}, {typKonzultace}<br/>',
                            '{zaverecnaDohoda}'
                        ],
                        store: 'ConsultationCareStore'
                    },
                    {
                        xtype: 'container',
                        flex: 50,
                        itemId: 'consultationCareInfo',
                        margin: 5,
                        style: 'border-top: solid black 5px;',
                        scrollable: 'vertical'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'fullClientInfo'
            }
        ]
    },

    constructor: function() {
        this.callParent(arguments);
        this.quickInfoTemplate = new Ext.XTemplate(
            '{Name}'
        );
        this.fullInfoTemplate = new Ext.XTemplate(
            '<div style="padding: 5px;"><h2>{Name}</h2>',
            '<tpl if="contactPerson">',
            '<a href="http://mapy.cz/?q={street}, {city}" style="color: #99CCFF; text-decoration: none;" target="_blank">{street}, {city}</a></tpl><br/>',
            '<tpl if="contactPerson">Pečující: {contactPerson}<br />',
            '<tpl if="mobileNumber">{mobilePrefix}{mobileNumber}<tpl if="phoneNumber">, </tpl></tpl>',
            '<tpl if="phoneNumber">{phonePrefix}{phoneNumber}</tpl>',
            '</tpl><tpl if="!contactPerson">Pečující osoba nezadána</tpl></div>'
        );
    },

    initialize: function() {

        this.callParent();
        Ext.Viewport.setMenu(this.createMenu(), {
            side: 'left',
            cover: false
        });
    },

    createMenu: function() {
        var items = [
            {
                xtype: 'button',
                itemId: 'back',
                ui: 'back',
                text: 'Zpět'
            },
            {
                xtype: 'button',
                itemId: 'pacient',
                text: 'Pacient'
            },
            {
                xtype: 'button',
                itemId: 'nurse',
                text: 'Průběhy'
            },
            {
                xtype: 'button',

                itemId: 'drug',
                text: 'Medikace'
            },
            {
                xtype: 'button',
                itemId: 'doctor',
                text: 'Lékařské'
            },
            {
                xtype: 'button',
                itemId: 'consultation',
                text: 'Konzultace'
            },
            {
                xtype: 'button',
                itemId: 'newRecord',
                text: 'Přidat...'
            }
        ];

        return Ext.create('Ext.Menu', {
            id: 'clientDetailMenu',
            width: 200,
            scrollable: 'vertical',
            items: items
        });
    }

});